# Testing GPU

## Import TensorFlow and other libraries

In [1]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [80]:
import numpy as np

class RatioLoss(tf.keras.losses.Loss):

  def __call__(self, y_true, y_pred):

    ratio_pred = []
    ratio_true = []
    for i in range(1, y_true.shape[-1]):
      ratio_pred.append(
          tf.math.divide_no_nan(
          y_pred[...,i], y_pred[...,i-1]
        )
      )
      ratio_true.append(
          tf.math.divide_no_nan(
          y_true[...,i], y_true[...,i-1]
        )
      )
    ratio_pred = tf.stack(ratio_pred, 1)   
    ratio_true = tf.stack(ratio_true, 1)

    return tf.math.reduce_std(tf.abs(ratio_true - ratio_pred))

In [81]:
ratio_loss = RatioLoss()

a = np.array([
        [
            [
                [1., 1., 1.],
                [1., 1., 1.],
                [1., 1., 1.],
            ],
            [
                [4., 4., 4.],
                [4., 4., 4.],
                [4., 4., 4.],
            ],
            [
                [4., 4., 4.],
                [4., 4., 4.],
                [4., 4., 4.],
            ],
            [
                [2., 2., 2.],
                [2., 2., 2.],
                [2., 2., 2.],
            ],
        ],
        [
            [
                [1., 1., 1.],
                [1., 1., 1.],
                [1., 1., 1.],
            ],
            [
                [4., 4., 4.],
                [4., 4., 4.],
                [4., 4., 4.],
            ],
            [
                [4., 4., 4.],
                [4., 4., 4.],
                [4., 4., 4.],
            ],
            [
                [2., 2., 2.],
                [2., 2., 2.],
                [2., 2., 2.],
            ],
        ]
    ])

b = np.array([
        [
            [
                [1., 1., 1.],
                [1., 1., 1.],
                [1., 1., 1.],
            ],
            [
                [2., 2., 2.],
                [2., 2., 2.],
                [2., 2., 2.],
            ],
            [
                [4., 4., 4.],
                [4., 4., 4.],
                [4., 4., 4.],
            ],
            [
                [3., 3., 3.],
                [3., 3., 3.],
                [3., 3., 3.],
            ],
        ],
        [
            [
                [1., 1., 1.],
                [1., 1., 1.],
                [1., 1., 1.],
            ],
            [
                [3., 3., 3.],
                [3., 3., 3.],
                [3., 3., 3.],
            ],
            [
                [4., 4., 4.],
                [4., 4., 4.],
                [4., 4., 4.],
            ],
            [
                [3., 3., 3.],
                [3., 3., 3.],
                [3., 3., 3.],
            ],
        ]
    ])
a = np.moveaxis(a, 1, -1)
b = np.moveaxis(b, 1, -1)
ratio_loss(a, b)

tf.Tensor(
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]], shape=(2, 3, 3), dtype=float64)
tf.Tensor(
[[[2.         2.         2.        ]
  [2.         2.         2.        ]
  [2.         2.         2.        ]]

 [[1.33333333 1.33333333 1.33333333]
  [1.33333333 1.33333333 1.33333333]
  [1.33333333 1.33333333 1.33333333]]], shape=(2, 3, 3), dtype=float64)
tf.Tensor(
[[[0.75 0.75 0.75]
  [0.75 0.75 0.75]
  [0.75 0.75 0.75]]

 [[0.75 0.75 0.75]
  [0.75 0.75 0.75]
  [0.75 0.75 0.75]]], shape=(2, 3, 3), dtype=float64)
tf.Tensor(
[[[[2.         2.         2.        ]
   [2.         2.         2.        ]
   [2.         2.         2.        ]]

  [[2.         2.         2.        ]
   [2.         2.         2.        ]
   [2.         2.         2.        ]]

  [[0.75       0.75       0.75      ]
   [0.75       0.75       0.75      ]
   [0.75       0.75       0.75      ]]]


 [[[3.         3.         3.        ]
   [3.         3.         3.        ]
   [3

<tf.Tensor: shape=(), dtype=float64, numpy=0.6248456599556662>